import turtle

turtle.pensize(10)
turtle.speed(1)
turtle.color('black')
turtle.begin_fill()
turtle.fillcolor('lime')
turtle.left(150)
turtle.forward(180)
turtle.line(0,90)
turtle.setheading(60)
turtle.circle(-90,180)
turtle.forward(180)
turtle.end_fill()
turtle.mainloop()